# Generated by Django 5.1.7 on 2025-05-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_is_verified_field'),
    ]

    operations = [
    ]
