# Generated by Django 5.1.7 on 2025-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_is_verified_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь подтвердил email', verbose_name='Подтверждён'),
        ),
    ]
