# Generated by Django 5.1.7 on 2025-04-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='count_views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Укажите количество просмотров поста', verbose_name='Количество просмотров'),
        ),
    ]
