# Generated by Django 5.1.7 on 2025-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отображать товар в каталоге', verbose_name='Активный товар'),
        ),
    ]
